- name: Django Application server set up
  hosts: myhosts
  tasks:
    - name: Update packages
      become: true
      ansible.builtin.apt:
        upgrade: yes

    - name: Getting code base
      ansible.builtin.git:
        accept_hostkey: true
        clone: yes
        update: yes
        name: git@github.com:gumisofts/gumisofts.com.git
        dest: /home/gumiapun/gumisofts.com/dev
        force: yes

    - name: Install Pip requirements
      ansible.builtin.pip:
        virtualenv: ~/app/env
        requirements: ~/app/requirements.txt
    - name: Setup unix socket
      become: true
      ansible.builtin.copy:
        force: true
        src: ../deployment/app.socket
        dest: /etc/systemd/system/app.socket
    - name: Copy Environmental Variables
      copy:
        dest: ~/app/config/
        force: true
        src: ../config/.env
        
    - name: Upload nginx conf
      become: true
      ansible.builtin.copy:
        force: true
        src: ../deployment/app.conf
        dest: /etc/nginx/conf.d/

    - name: Enable Nginx Services on Boot
      ansible.builtin.systemd_service:
        name: nginx
        enabled: true
        state: started
    - name: Enable Bita_markets Service
      become: true
      ansible.builtin.systemd_service:
        name: bita_markets
        enabled: true
        state: started
        daemon_reload: true
